//
// Created by nickr on 2022-02-14.
//

#ifndef AVR_PROJECT_MAIN_1_TIMER2COUNT_H
#define AVR_PROJECT_MAIN_1_TIMER2COUNT_H

#define FUNDFREQ 8000000
#define FREQDIV 1024
#define COUNTSEC FREQDIV/FUNDFREQ
#define LONGESTTIME COUNTSEC*65536

void ButtonSwap();

#endif //AVR_PROJECT_MAIN_1_TIMER2COUNT_H
